server:
  port: 8087
  max-http-header-size: 102400
  address: 0.0.0.0

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/home_school?characterEncoding=utf8&useSSL=true
#    username: root
#    password: 123456
